import Link from "next/link";

const guides = [
  { title: "Recovery harassment", tag: "Debt collection", summary: "Recognize intimidation, public shaming, contact-list misuse, and calls outside reasonable hours.", signs: ["Threats or abusive language", "Messages to family, friends, or colleagues", "Anonymous callers or false legal claims"], actions: "Save calls and messages, ask for written loan details, complain to the lender, and escalate when unresolved.", link: "/debt-recovery-rules", cta: "Read debt-recovery rules" },
  { title: "Fake settlement calls", tag: "Payment safety", summary: "Spot callers who promise to close a loan if you pay a personal UPI ID, wallet, or urgent ‘processing fee’. ", signs: ["Settlement offer is not on the lender’s official domain", "Payment requested to a personal account", "Caller asks for OTP, PIN, or screen sharing"], actions: "Stop the conversation, verify through the lender’s official website, and never share authentication secrets.", link: "/tools/repayment-channel-checker", cta: "Check a repayment channel" },
  { title: "Digital arrest scams", tag: "Impersonation", summary: "A real police, court, RBI, or government officer will not arrest you over a video call or demand money to ‘clear’ an investigation.", signs: ["Video call with a uniformed impersonator", "Threats of immediate arrest or account freeze", "Demand for secrecy, money, or remote access"], actions: "End the call, contact the institution using a trusted number, preserve the recording or messages, and report online fraud.", link: "/complaint-wizard", cta: "Prepare a complaint" },
  { title: "Loan-app permissions", tag: "Privacy", summary: "A loan app should not need unrestricted access to contacts, photos, messages, or accessibility features to provide a legitimate service.", signs: ["Contacts or gallery access is mandatory", "App asks to disable security settings", "Permission request does not match the feature"], actions: "Deny unnecessary permissions, uninstall unsafe apps, change exposed passwords, and preserve the app URL and screenshots.", link: "/app-permissions", cta: "Review app permissions" },
  { title: "UPI and payment fraud", tag: "Financial fraud", summary: "Receiving money never requires entering a UPI PIN. A collect request or QR scan can send money out of your account.", signs: ["Unexpected collect request", "Caller asks you to scan a QR code to receive a refund", "Urgent request for OTP, PIN, or screen sharing"], actions: "Do not approve or scan, contact your bank, call 1930 immediately after a loss, and file the cybercrime report.", link: "/complaint-tutorials", cta: "See filing tutorials" },
  { title: "Identity theft", tag: "Account protection", summary: "Identity theft can include fake accounts, SIM misuse, leaked KYC documents, impersonation, or unauthorized loan applications.", signs: ["Unknown OTPs or account alerts", "New loan or SIM activity you did not request", "Your documents appear on an unfamiliar profile"], actions: "Secure email and bank accounts, contact the provider, report the impersonation, and keep a timeline of every alert.", link: "/complaint-wizard", cta: "Start identity complaint" },
];

export default function SafetyLibraryPage() {
  return <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8"><section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Borrower safety education</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">Safety Education Library</h1><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Short, practical guides for the scams and collection tactics borrowers commonly face. Start with the guide that matches what is happening now.</p></section><section className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{guides.map((guide) => <article key={guide.title} className="flex h-full flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-700">{guide.tag}</span><span className="text-xs text-slate-400">Guide</span></div><h2 className="mt-4 text-xl font-bold text-slate-950">{guide.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{guide.summary}</p><h3 className="mt-4 text-sm font-semibold text-slate-950">Warning signs</h3><ul className="mt-2 grid gap-1.5 text-sm leading-5 text-slate-600">{guide.signs.map((sign) => <li key={sign} className="flex gap-2"><span className="text-rose-600">•</span>{sign}</li>)}</ul><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm leading-6 text-slate-700"><span className="font-semibold text-slate-950">Do this: </span>{guide.actions}</div><Link href={guide.link} className="mt-auto pt-5 text-sm font-semibold text-blue-700 underline underline-offset-2">{guide.cta} →</Link></article>)}</section><section className="mt-8 rounded-2xl border border-rose-200 bg-rose-50 p-5 sm:p-6"><h2 className="text-xl font-bold text-rose-950">Threat happening now?</h2><p className="mt-2 text-sm leading-6 text-rose-900">Use the emergency flow for 1930, cybercrime reporting, evidence capture, and trusted-contact actions.</p><Link href="/emergency-help" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-rose-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-rose-800">Open emergency help</Link></section><p className="mt-5 text-xs leading-5 text-slate-500">These guides are general safety information, not legal advice. Use official websites and verified contact details before sharing personal or financial information.</p></main>;
}
