import type { LoanApp, ComplaintSummary, RegulatoryAction } from "@prisma/client";

export const toPublicLoanAppListItemDto = (app: LoanApp) => ({
  id: app.id,
  slug: app.slug,
  name: app.name,
  logoUrl: app.logoUrl,
  developerName: app.developerName,
  companyName: app.companyName,
  legalEntityName: app.legalEntityName,
  businessType: app.businessType,
  claimedNbfcPartner: app.claimedNbfcPartner,
  associatedRegulatedEntity: app.associatedRegulatedEntity,
  status: app.status,
  verificationStatus: app.verificationStatus,
  claimStatus: app.claimStatus,
  trustScore: app.trustScore,
  riskLevel: app.riskLevel,
  averageRating: app.averageRating,
  reviewCount: app.reviewCount,
  summaryNote: "Scores and labels are awareness indicators based on available public details and user-submitted reviews.",
  updatedAt: app.updatedAt,
});

export const toPublicLoanAppProfileDto = (app: LoanApp & { complaintSummaries: ComplaintSummary[]; regulatoryActions?: RegulatoryAction[] }) => ({
  ...toPublicLoanAppListItemDto(app),
  packageName: app.packageName,
  websiteUrl: app.websiteUrl,
  playStoreUrl: app.playStoreUrl,
  appStoreUrl: app.appStoreUrl,
  rbiRegistrationNumber: app.rbiRegistrationNumber,
  rbiRegistrationVerifiedAt: app.rbiRegistrationVerifiedAt,
  rbiRegistrationSourceUrl: app.rbiRegistrationSourceUrl,
  interestRateRange: app.interestRateRange,
  processingFees: app.processingFees,
  latePaymentCharges: app.latePaymentCharges,
  loanTenure: app.loanTenure,
  privacyDisclosure: app.privacyDisclosure,
  contactAccessDisclosure: app.contactAccessDisclosure,
  recoveryPracticeInfo: app.recoveryPracticeInfo,
  knownComplaintCategories: app.knownComplaintCategories,
  publicWarningLabels: app.publicWarningLabels,
  dataSource: app.dataSource,
  lastReviewedAt: app.lastReviewedAt,
  grievanceEmail: app.grievanceEmail,
  supportEmail: app.supportEmail,
  supportPhone: app.supportPhone,
  registeredAddress: app.registeredAddress,
  complaintSummaries: app.complaintSummaries.map((summary) => ({
    tag: summary.tag,
    count: summary.count,
    percentage: summary.percentage,
    lastCalculatedAt: summary.lastCalculatedAt,
  })),
  publicSafetyNote:
    "This profile shows public details, app-provided claims, and user-reported patterns. It does not make final legal findings.",
  regulatoryActions: (app.regulatoryActions ?? []).map((action) => ({
    id: action.id,
    authorityName: action.authorityName,
    authorityJurisdiction: action.authorityJurisdiction,
    actionType: action.actionType,
    severity: action.severity,
    status: action.status,
    title: action.title,
    summary: action.summary,
    orderNumber: action.orderNumber,
    sourceUrl: action.sourceUrl,
    sourceDocumentUrl: action.sourceDocumentUrl,
    sourcePublishedAt: action.sourcePublishedAt,
    effectiveFrom: action.effectiveFrom,
    effectiveUntil: action.effectiveUntil,
    verifiedAt: action.verifiedAt,
  })),
});
