"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Incident = "regulated" | "scheme" | "cyber-fraud" | "harassment" | "data-misuse" | "other";

const incidentOptions: { value: Incident; label: string; hint: string }[] = [
  { value: "regulated", label: "Complaint against a bank or NBFC", hint: "Service, repayment, account, or recovery-agent issue" },
  { value: "scheme", label: "Suspected illegal loan or money scheme", hint: "Unauthorized app, deposit-taking, or collection scheme" },
  { value: "cyber-fraud", label: "Online financial fraud", hint: "UPI, card, wallet, bank transfer, or payment scam" },
  { value: "harassment", label: "Threats or recovery harassment", hint: "Threats, public shaming, abusive calls, or contact-list misuse" },
  { value: "data-misuse", label: "Personal-data or identity misuse", hint: "Impersonation, leaked data, or unauthorized use of contacts/photos" },
  { value: "other", label: "Something else", hint: "Start with the lender grievance channel and review the options" },
];

const portalByIncident: Record<Incident, { name: string; href: string; reason: string }[]> = {
  regulated: [{ name: "Lender grievance officer", href: "/grievance-directory", reason: "Start with the bank or NBFC’s official complaint channel." }, { name: "RBI CMS / Ombudsman", href: "https://cms.rbi.org.in/", reason: "Use when the regulated entity does not resolve the complaint." }],
  scheme: [{ name: "RBI Sachet", href: "https://sachet.rbi.org.in/", reason: "Report suspected unauthorized deposit-taking or money-collection activity." }, { name: "National Cyber Crime Portal", href: "https://www.cybercrime.gov.in/", reason: "Use when the scheme also involves online fraud, threats, or data misuse." }],
  "cyber-fraud": [{ name: "1930 financial cyber fraud helpline", href: "tel:1930", reason: "Call immediately when money has moved through a digital channel." }, { name: "National Cyber Crime Portal", href: "https://www.cybercrime.gov.in/", reason: "Submit the complete online complaint and evidence." }],
  harassment: [{ name: "Lender grievance officer", href: "/grievance-directory", reason: "Report the recovery-agent conduct to the lender in writing." }, { name: "National Cyber Crime Portal", href: "https://www.cybercrime.gov.in/", reason: "Use for threats, extortion, impersonation, or online harassment." }],
  "data-misuse": [{ name: "National Cyber Crime Portal", href: "https://www.cybercrime.gov.in/", reason: "Report identity, contact-list, image, or account misuse." }, { name: "Lender grievance officer", href: "/grievance-directory", reason: "Ask the lender to investigate and stop unauthorized processing." }],
  other: [{ name: "Lender grievance officer", href: "/grievance-directory", reason: "Use the provider’s official complaint route first." }, { name: "RBI CMS / Ombudsman", href: "https://cms.rbi.org.in/", reason: "Consider escalation if the regulated entity does not resolve it." }],
};

const evidenceByIncident: Record<Incident, string[]> = {
  regulated: ["Loan or account statement", "Your complaint and the lender’s acknowledgement", "Call logs, messages, emails, and agent details", "Payment receipts or disputed entries"],
  scheme: ["App or website URL and screenshots", "Promises, advertisements, and fee demands", "UPI IDs, bank accounts, phone numbers, and payment receipts", "Names used by the operator and dates of contact"],
  "cyber-fraud": ["Transaction ID, date, amount, and debited account or wallet", "Bank or payment-app statement", "Scam number, URL, UPI ID, profile, or message", "Screenshots and the 1930 acknowledgement"],
  harassment: ["Call logs and recordings where lawful", "Threatening messages, caller numbers, and social posts", "Names or contacts who were approached", "Loan account and recovery-agent details"],
  "data-misuse": ["Screenshots of the leaked or misused information", "Source URL, profile, phone number, or app", "Consent or permission history", "Dates, affected contacts, and any resulting harm"],
  other: ["A dated incident timeline", "Relevant account, app, or lender details", "Messages, receipts, screenshots, and contact details", "Copies of every complaint and reply"],
};

export default function ComplaintPreparationWizard() {
  const [step, setStep] = useState(1);
  const [incident, setIncident] = useState<Incident>("regulated");
  const [form, setForm] = useState({ name: "", entity: "", date: "", amount: "", description: "", contact: "" });
  const [copied, setCopied] = useState(false);
  const recommendation = portalByIncident[incident];
  const draft = useMemo(() => `Subject: Complaint regarding ${form.entity || "the incident"}\n\nI am writing to report ${incidentOptions.find((option) => option.value === incident)?.label.toLowerCase() || "an incident"}.\n\nDate of incident: ${form.date || "[add date]"}\nEntity / app / account: ${form.entity || "[add name]"}\nAmount involved: ${form.amount || "[add amount or write Not applicable]"}\n\nDetails:\n${form.description || "[Describe what happened in date order. Include names, phone numbers, URLs, payment IDs, and the action you want taken.]"}\n\nI have attached the available records and request a written acknowledgement, investigation, and details of the corrective action. Please contact me at ${form.contact || "[add safe contact detail]"}.\n\nName: ${form.name || "[add name or preferred display name]"}`, [form, incident]);

  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const copyDraft = async () => { await navigator.clipboard?.writeText(draft); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const saveDraft = () => { localStorage.setItem("trust-loans-complaint-wizard", JSON.stringify({ incident, form, draft, savedAt: new Date().toISOString() })); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };

  return <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
    <section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Complaint preparation</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">Build your complaint in three steps</h1><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Answer a few questions to identify a reporting channel, prepare a factual draft, and see the evidence to gather.</p></section>
    <div className="mt-8 flex items-center gap-2 text-xs font-semibold text-slate-500" aria-label="Wizard progress">{["Issue", "Details", "Draft & checklist"].map((label, index) => <div key={label} className={`flex min-w-0 flex-1 items-center gap-2 ${step >= index + 1 ? "text-blue-700" : ""}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${step >= index + 1 ? "bg-blue-700 text-white" : "bg-slate-200 text-slate-500"}`}>{index + 1}</span><span className="hidden sm:block">{label}</span>{index < 2 && <span className="h-px flex-1 bg-slate-200" />}</div>)}</div>
    {step === 1 && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold text-slate-950">What best describes the issue?</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{incidentOptions.map((option) => <button key={option.value} type="button" onClick={() => setIncident(option.value)} className={`rounded-xl border p-4 text-left transition ${incident === option.value ? "border-blue-600 bg-blue-50 ring-2 ring-blue-100" : "border-slate-200 hover:border-slate-300"}`}><span className="block text-sm font-semibold text-slate-950">{option.label}</span><span className="mt-1 block text-xs leading-5 text-slate-600">{option.hint}</span></button>)}</div><button type="button" onClick={() => setStep(2)} className="mt-6 min-h-11 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Continue</button></section>}
    {step === 2 && <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h2 className="text-xl font-bold text-slate-950">Add the facts</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-700">Your name or display name<input value={form.name} onChange={(event) => update("name", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base" placeholder="Use a privacy-safe name if needed" /></label><label className="text-sm font-medium text-slate-700">Entity, app, or account<input value={form.entity} onChange={(event) => update("entity", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base" placeholder="Name shown on the app or statement" /></label><label className="text-sm font-medium text-slate-700">Incident date<input type="date" value={form.date} onChange={(event) => update("date", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base" /></label><label className="text-sm font-medium text-slate-700">Amount involved<input inputMode="decimal" value={form.amount} onChange={(event) => update("amount", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base" placeholder="₹ amount or Not applicable" /></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">Safe contact detail<input value={form.contact} onChange={(event) => update("contact", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-base" placeholder="Email or phone you are comfortable sharing" /></label><label className="text-sm font-medium text-slate-700 sm:col-span-2">What happened? <textarea value={form.description} onChange={(event) => update("description", event.target.value)} className="mt-1 min-h-32 w-full rounded-xl border border-slate-300 p-3 text-base" placeholder="Write facts in date order. Avoid guesses or insults." /></label></div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={() => setStep(1)} className="min-h-11 rounded-xl border border-slate-300 px-5 py-2.5 text-sm font-semibold text-slate-700">Back</button><button type="button" onClick={() => setStep(3)} className="min-h-11 rounded-xl bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white hover:bg-slate-800">Generate draft</button></div></section>}
    {step === 3 && <section className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_0.85fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">Recommended channels</h2><p className="mt-1 text-sm text-slate-600">Start with the first option, then escalate when appropriate.</p></div><button type="button" onClick={() => setStep(2)} className="text-sm font-semibold text-blue-700 underline">Edit facts</button></div><div className="mt-4 grid gap-3">{recommendation.map((item, index) => <a key={item.name} href={item.href} target={item.href.startsWith("http") ? "_blank" : undefined} rel={item.href.startsWith("http") ? "noreferrer" : undefined} className="rounded-xl border border-slate-200 p-4 hover:border-blue-300 hover:bg-blue-50"><span className="block text-sm font-semibold text-slate-950">{index + 1}. {item.name}</span><span className="mt-1 block text-xs leading-5 text-slate-600">{item.reason}</span></a>)}</div><div className="mt-6 flex flex-wrap gap-3"><button type="button" onClick={copyDraft} className="min-h-11 rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-800">{copied ? "Copied / saved" : "Copy complaint"}</button><button type="button" onClick={saveDraft} className="min-h-11 rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700">Save draft on this device</button></div><label className="mt-5 block text-sm font-semibold text-slate-950">Ready-to-submit draft<textarea readOnly value={draft} className="mt-2 min-h-80 w-full rounded-xl border border-slate-300 bg-slate-50 p-3 text-sm leading-6 text-slate-700" /></label></article><aside className="rounded-2xl border border-blue-100 bg-blue-50/70 p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-950">Evidence checklist</h2><p className="mt-1 text-sm text-slate-600">Gather only what is relevant. Redact OTPs, passwords, and unrelated private data.</p><ul className="mt-4 grid gap-3">{evidenceByIncident[incident].map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-slate-700"><span className="mt-1 text-blue-700">□</span>{item}</li>)}</ul><Link href="/complaint-tutorials" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Watch filing tutorials</Link></aside></section>}
    <p className="mt-6 text-xs leading-5 text-slate-500">This wizard creates drafting support, not legal advice. Review every field, remove anything inaccurate, and submit only through the official portal.</p>
  </main>;
}
