import Link from "next/link";

type Tutorial = { title: string; summary: string; portal: string; portalLabel: string; search: string; steps: string[] };

const tutorials: Tutorial[] = [
  { title: "RBI CMS / Ombudsman", summary: "For an unresolved complaint against an RBI-regulated bank, NBFC, or payment system participant.", portal: "https://cms.rbi.org.in/", portalLabel: "Open RBI CMS", search: "RBI Complaint Management System how to file a complaint", steps: ["Complain to the regulated entity first and keep its acknowledgement.", "After the required waiting period or an unsatisfactory reply, select File a Complaint on CMS.", "Enter your contact details, entity, facts, supporting documents, and the remedy requested.", "Save the registration number so you can track the complaint or appeal."] },
  { title: "RBI Sachet", summary: "For suspected unauthorized deposit-taking, loan schemes, or money-collection activity.", portal: "https://sachet.rbi.org.in/", portalLabel: "Open RBI Sachet", search: "RBI Sachet portal how to file complaint", steps: ["Collect the scheme name, app or website URL, phone numbers, payment IDs, and screenshots.", "Open the Sachet complaint form and choose the closest activity or entity category.", "Describe what was promised, what money or data was requested, and where it happened.", "Submit the form and retain the acknowledgement for follow-up."] },
  { title: "National Cyber Crime Portal", summary: "For online harassment, impersonation, extortion, data misuse, hacking, and other cybercrime complaints.", portal: "https://www.cybercrime.gov.in/", portalLabel: "Open Cyber Crime Portal", search: "National Cyber Crime Reporting Portal how to file complaint India", steps: ["Use Report Other Cybercrimes for online financial fraud, harassment, hacking, or impersonation.", "Register with a valid Indian mobile number and OTP, then select the category and state.", "Add dates, phone numbers, URLs, account handles, transaction details, and readable evidence.", "Submit and save the complaint ID and downloaded copy."] },
  { title: "1930 financial cyber fraud", summary: "For money already transferred through UPI, card, wallet, bank transfer, or another digital channel.", portal: "tel:1930", portalLabel: "Call 1930 now", search: "1930 cyber financial fraud reporting India tutorial", steps: ["Call 1930 immediately; speed can help banks and intermediaries attempt to hold funds.", "Keep the debited bank or wallet, account or UPI ID, transaction ID, date, amount, and screenshots ready.", "Write down the acknowledgement or log-in ID sent by SMS or email.", "Complete the linked cybercrime.gov.in complaint and keep the reference number."] },
  { title: "Bank / NBFC financial-crime grievance", summary: "For unauthorized debits, fake collection accounts, recovery-agent misconduct, or suspected fraud involving a bank or NBFC.", portal: "/grievance-directory", portalLabel: "Find grievance contacts", search: "India bank NBFC fraud complaint financial crime reporting process", steps: ["Use the lender’s official website or grievance directory—not a number sent by an unknown caller.", "Send a written complaint with the account, incident timeline, disputed amount, and evidence.", "Ask for a ticket number, reversal or investigation, and written confirmation of the outcome.", "If unresolved, use RBI CMS for an eligible regulated entity; use 1930 or the cybercrime portal for digital fraud."] },
];

export default function ComplaintTutorialsPage() {
  return (
    <main className="mx-auto w-full max-w-6xl px-4 py-8 sm:px-6 sm:py-12 lg:px-8">
      <section className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-700">Step-by-step help</p><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-5xl">How to file a complaint</h1><p className="mt-4 text-base leading-7 text-slate-600 sm:text-lg">Choose the channel that matches your issue. Each tutorial includes an inline YouTube player, a checklist, and the official destination.</p></section>
      <div className="mt-8 grid gap-6">{tutorials.map((tutorial) => { const external = tutorial.portal.startsWith("http"); return <article key={tutorial.title} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><div className="aspect-video bg-slate-950 lg:aspect-auto lg:min-h-[300px]"><iframe className="h-full w-full" src={`https://www.youtube.com/embed?listType=search&list=${encodeURIComponent(tutorial.search)}`} title={`${tutorial.title} tutorial video`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /></div><div className="p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-950">{tutorial.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{tutorial.summary}</p></div><a href={tutorial.portal} target={external ? "_blank" : undefined} rel={external ? "noreferrer" : undefined} className="inline-flex min-h-11 shrink-0 items-center rounded-xl border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-800 hover:bg-slate-50">{tutorial.portalLabel}</a></div><h3 className="mt-5 text-sm font-semibold text-slate-950">Filing checklist</h3><ol className="mt-2 grid gap-2 text-sm leading-6 text-slate-600">{tutorial.steps.map((step, index) => <li key={step}><span className="mr-2 font-semibold text-blue-700">{index + 1}.</span>{step}</li>)}</ol></div></div></article>; })}</div>
      <div className="mt-8 flex flex-wrap items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-5 text-sm text-slate-600"><span>Need urgent safety guidance?</span><Link href="/emergency-help" className="font-semibold text-blue-700 underline">Open emergency help</Link><Link href="/debt-recovery-rules" className="font-semibold text-blue-700 underline">Read debt-recovery rules</Link></div>
      <Link href="/complaint-wizard" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-blue-800">Prepare a complaint draft</Link>
      <p className="mt-4 text-xs leading-5 text-slate-500">The embedded players use YouTube’s search-based player so the video list can stay current. Verify the channel and destination before submitting sensitive information.</p>
    </main>
  );
}
